### ISSUE TITLE
弹窗弹出一次 第二次再点击就监测不到崩溃了？

### ISSUE THREAD

**Issue by Nglszs** [kshipeng/SPUncaughtExceptionHandler#1]

**Comment by kshipeng** [comment]
不要在debug环境下测试。因为系统的debug会优先去拦截。要运行一次后，关闭debug状态。即直接点击我们在模拟器或真机上build的app去运行。

**Comment by Nglszs** [comment]
恩，可以了

**Comment by kshipeng** [comment]
现已添加cocoapods支持: pod 'SPUncaughtExceptionHandler', '~> 0.0.1'    觉得还不错的话就给颗星星呗😊
